imports:
    - { resource: config.yml }

doctrine_cache:
    providers:
        vendor_filesystem_metadata_cache:
            type: array
            namespace: doctrine_cache.ns.fsmeta
        vendor_filesystem_result_cache:
            type: array
            namespace: doctrine_cache.ns.fsresult
        vendor_filesystem_query_cache:
            type: array
            namespace: doctrine_cache.ns.fsquery

framework:
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
